field: 2b752466-a680-4956-b353-c24d023b4612 # Blocks
fieldLayouts:
  bbd2842d-411a-4873-9c5f-64311b0ddb06:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 29821e75-a038-4d14-89b3-43b36d7caac3 # Card Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 331dfc6e-7aba-4c19-988d-b94fb6d82906
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 9e4031da-f642-41d4-b5bf-bd0594b32530 # Card Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ea209a8-06b5-462c-b563-ce6fd828ae99
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7b695023-8455-4af6-9ed2-7f1224b2c291 # Card Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16793229-05ce-4d11-be7b-42a49cab177a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c8a8c361-64b1-46fe-9856-68d9463106ef # Card Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0258f393-f17d-4784-b060-34e1b7d57c00
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: a4c52ef9-e5ec-4b8a-83a0-1758422d0a84 # Popup
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a14bb8ee-8389-4240-be7e-d58496607f04
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 09c301c2-9097-4cf9-bf1d-1ce58abf51cf # Mobile Options
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cb3c0e98-715e-4359-a524-7787d756f84e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 4f4445f6-0c67-4594-947d-6fb81569b224 # Card Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc70e13c-c2e7-4604-8df3-f2d21e6d6b6d
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 93c904bd-0815-4869-9b0e-215ecdb3b858 # Image Crop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37380edc-5269-4536-b770-76faf5b60003
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 67060e9a-64c6-4284-bb26-6dac5a244958 # Button Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b80fb344-97a4-4910-8092-30c595c2e7bc
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 024a35ce-6f01-4d9e-8254-348490d74545 # Button Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68ed8373-8138-4ec1-ac20-cb59e80a7dd5
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 344246e9-17c3-4abc-b658-80887c35ded1 # Embed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5861797-89e8-4dae-810c-0f1bfa2187ae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 935079c4-0bdc-4671-a897-af6451df6641
        userCondition: null
fields:
  4f4445f6-0c67-4594-947d-6fb81569b224: # Card Background Colour
    columnSuffix: whbwacqm
    contentColumnType: string
    fieldGroup: null
    handle: cardBackgroundColour
    instructions: 'Set card background colour'
    name: 'Card Background Colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - bg-quaternary-main
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  7b695023-8455-4af6-9ed2-7f1224b2c291: # Card Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardLink
    instructions: 'Set the card link'
    name: 'Card Link'
    searchable: false
    settings:
      allowCustomText: true
      allowTarget: false
      autoNoReferrer: false
      customTextMaxLength: 0
      customTextRequired: false
      defaultLinkName: asset
      defaultText: 'Read More'
      enableAllLinkTypes: false
      enableAriaLabel: false
      enableElementCache: false
      enableTitle: false
      typeSettings:
        asset:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        category:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
        custom:
          allowAliases: false
          disableValidation: false
          enabled: true
        email:
          allowAliases: false
          disableValidation: false
          enabled: true
        entry:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: true
          sources: '*'
        site:
          enabled: false
          sites: '*'
        tel:
          allowAliases: false
          disableValidation: false
          enabled: true
        url:
          allowAliases: false
          disableValidation: false
          enabled: true
        user:
          allowCrossSiteLink: false
          allowCustomQuery: false
          enabled: false
          sources: '*'
    translationKeyFormat: null
    translationMethod: none
    type: lenz\linkfield\fields\LinkField
  09c301c2-9097-4cf9-bf1d-1ce58abf51cf: # Mobile Options
    columnSuffix: xdbnvefb
    contentColumnType: string
    fieldGroup: null
    handle: mobileOptions
    instructions: 'Options for mobile styling'
    name: 'Mobile Options'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Stack
            -
              - value
              - stackCard
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  9e4031da-f642-41d4-b5bf-bd0594b32530: # Card Image
    columnSuffix: ppjkignv
    contentColumnType: string
    fieldGroup: null
    handle: cardImage
    instructions: 'Set the card image'
    name: 'Card Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:c4100103-0b95-4960-bee7-74876c13e673' # General Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c4100103-0b95-4960-bee7-74876c13e673' # General Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  024a35ce-6f01-4d9e-8254-348490d74545: # Button Colour
    columnSuffix: uatqcffi
    contentColumnType: string
    fieldGroup: null
    handle: buttonColour
    instructions: null
    name: 'Button Colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Master
            -
              - value
              - master
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Inherit
            -
              - value
              - ''
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - bg-quaternary-main
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  93c904bd-0815-4869-9b0e-215ecdb3b858: # Image Crop
    columnSuffix: ohlzhnam
    contentColumnType: string
    fieldGroup: null
    handle: imageCrop
    instructions: 'Select a crop'
    name: 'Image Crop'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - '16:9'
            -
              - value
              - medium
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Square (500)'
            -
              - value
              - square
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Large Square (1000)'
            -
              - value
              - largeSquare
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - portrait
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '4:3'
            -
              - value
              - fourThree
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  29821e75-a038-4d14-89b3-43b36d7caac3: # Card Title
    columnSuffix: smffuqud
    contentColumnType: text
    fieldGroup: null
    handle: cardTitle
    instructions: 'Set the card title'
    name: 'Card Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  67060e9a-64c6-4284-bb26-6dac5a244958: # Button Style
    columnSuffix: qsvfofvb
    contentColumnType: string
    fieldGroup: null
    handle: buttonStyle
    instructions: null
    name: 'Button Style'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - primary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Ghost
            -
              - value
              - ghost
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - secondary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Full Width'
            -
              - value
              - 'primary full-width'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  344246e9-17c3-4abc-b658-80887c35ded1: # Embed
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: embed
    instructions: 'Optional embed area used for buttons'
    name: Embed
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 241291029
      columns:
        __assoc__:
          -
            - f1612c84-6ba9-42e4-9dbe-f733f5d62f71 # Embed Code
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_23_embed}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  a4c52ef9-e5ec-4b8a-83a0-1758422d0a84: # Popup
    columnSuffix: dhjyncdt
    contentColumnType: boolean
    fieldGroup: null
    handle: popup
    instructions: 'Optionally display in popup'
    name: Popup
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  c8a8c361-64b1-46fe-9856-68d9463106ef: # Card Text
    columnSuffix: rcrdypci
    contentColumnType: text
    fieldGroup: null
    handle: cardText
    instructions: 'Enter card content'
    name: 'Card Text'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: cardBlock
name: Cards
sortOrder: 6
