field: 37b10ad2-1a23-4c38-8077-0b83551e9492 # Layout
fieldLayouts:
  7cb3cf93-3567-4445-968e-0f78c5bc14b9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bf1f676c-8a7b-477e-a45f-f185f1f30ada # UI Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4eec01c9-a2c9-40f0-860a-e27c645cd70d
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 89494ca9-cd3d-4e4e-9ae2-d5c8b001bf20 # Accordion Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 747a1123-5c27-41d3-959f-703a0f61f3dd
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 20697c37-c7bb-4d99-8b47-38f34a978d9b # Active UI Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f17d765-9e55-4b59-851a-d86f854f8583
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5ba0dd61-5654-407d-b514-2e8d9f43b4cc # Active Accordion Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 90d63e38-c244-45d3-b952-e78f34f853e3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 20e1d71d-a407-4f19-8fe4-fd94d332b130
        userCondition: null
fields:
  5ba0dd61-5654-407d-b514-2e8d9f43b4cc: # Active Accordion Background
    columnSuffix: dlxpjllo
    contentColumnType: string
    fieldGroup: null
    handle: activeAccordionBackground
    instructions: null
    name: 'Active Accordion Background'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - bg-quaternary-open
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  20697c37-c7bb-4d99-8b47-38f34a978d9b: # Active UI Colour
    columnSuffix: nzreamwz
    contentColumnType: string
    fieldGroup: null
    handle: activeUiColour
    instructions: null
    name: 'Active UI Colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - color-light-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - color-dark-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - color-primary-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - color-secondary-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - color-tertiary-open
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - color-quaternary-open
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  89494ca9-cd3d-4e4e-9ae2-d5c8b001bf20: # Accordion Background
    columnSuffix: ilqavrcy
    contentColumnType: string
    fieldGroup: null
    handle: accordionBackground
    instructions: null
    name: 'Accordion Background'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - bg-quaternary-main
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  bf1f676c-8a7b-477e-a45f-f185f1f30ada: # UI Colour
    columnSuffix: omsewpwq
    contentColumnType: string
    fieldGroup: null
    handle: uiColour
    instructions: null
    name: 'UI Colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - 'color-light-main  border-light-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - 'color-dark-main border-dark-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - 'color-primary-main border-primary-main '
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - 'color-secondary-main border-secondary-main '
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - 'color-tertiary-main border-tertiary-main '
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - 'color-quaternary-main border-quaternary-main'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: categoryAccordions
name: 'Category Accordions'
sortOrder: 6
