field: 954f3e11-2f00-41ba-b31e-e5777b252a9c # Header Content
fieldLayouts:
  d751874f-2e35-4396-89a5-3c28f020a6b9:
    tabs:
      -
        elements:
          -
            fieldUid: 41f3c60f-5f33-492c-a9b2-8e748e201c3f # Nav Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab4382ed-040d-48f3-b591-a85d90380afe
            warning: null
            width: 100
          -
            fieldUid: a686e391-2753-431a-a3c4-f15c1e695691 # Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68e5bba0-bdc0-482f-b55f-4abcc90c55e3
            warning: null
            width: 25
          -
            fieldUid: ffbd6503-405e-47a3-baae-e83ecfa38b7c # Nav Orientation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e5beb26-98d1-4fe1-8ffa-de846066b555
            warning: null
            width: 25
          -
            fieldUid: 6631b04d-3a12-4002-88a3-38445c3e8578 # Nav Gap
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c854f381-c589-4fbe-96cd-c7949d83a553
            warning: null
            width: 25
          -
            fieldUid: 2fb90cbc-02cb-44b2-9969-845a86f1dad0 # Hover Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a502955f-7758-4f79-aa68-4090aadb0a14
            warning: null
            width: 25
        name: Content
        uid: b7e27f82-13f3-4825-bad2-e4542e868a34
fields:
  2fb90cbc-02cb-44b2-9969-845a86f1dad0: # Hover Style
    columnSuffix: jknilvst
    contentColumnType: string
    fieldGroup: null
    handle: hoverStyle
    instructions: null
    name: 'Hover Style'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Highlight
            -
              - value
              - high-light
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Underline Text'
            -
              - value
              - underlineText
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Underline Block'
            -
              - value
              - underlineBlock
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  41f3c60f-5f33-492c-a9b2-8e748e201c3f: # Nav Items
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: navItems
    instructions: null
    name: 'Nav Items'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 1234621097
      columns:
        __assoc__:
          -
            - fc9cd23d-6117-4c13-8b54-f18a14823c53 # Nav Item
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 94176719-9813-4cb4-8f37-678a616686da # Sub Nav
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_4_navitems}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  6631b04d-3a12-4002-88a3-38445c3e8578: # Nav Gap
    columnSuffix: qnjawuhp
    contentColumnType: string
    fieldGroup: null
    handle: navGap
    instructions: null
    name: 'Nav Gap'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - flex-gap-000
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'XX Small'
            -
              - value
              - flex-gap-100
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Small'
            -
              - value
              - flex-gap-200
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Small
            -
              - value
              - flex-gap-300
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - flex-gap-400
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - flex-gap-500
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'X Large'
            -
              - value
              - flex-gap-600
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'XX Large'
            -
              - value
              - flex-gap-700
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a686e391-2753-431a-a3c4-f15c1e695691: # Width
    columnSuffix: jvdwpgvs
    contentColumnType: integer(10)
    fieldGroup: null
    handle: width
    instructions: null
    name: Width
    searchable: false
    settings:
      decimals: 0
      defaultValue: 80
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  ffbd6503-405e-47a3-baae-e83ecfa38b7c: # Nav Orientation
    columnSuffix: bgyjgyvc
    contentColumnType: string
    fieldGroup: null
    handle: navOrientation
    instructions: null
    name: 'Nav Orientation'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Space Evenly'
            -
              - value
              - space-evenly
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Space Between'
            -
              - value
              - space-between
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Centre
            -
              - value
              - centre
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Even Stretch'
            -
              - value
              - evenStretch
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: navigationBlock
name: 'Navigation Block'
sortOrder: 1
