field: ffc2b89f-46b4-4c4f-9ca6-71feacca2d27 # Page Builder
fieldLayouts:
  732b5413-4a7e-4096-a1f7-968163aaf4c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 686319ea-5532-4ed2-a09a-ac3f32674dcf # Panel Section
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5f6dd33-b9ba-4784-8a3f-de35940869f9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f21e9d85-57b2-4738-9f1a-b2aa29bab94e
        userCondition: null
fields:
  686319ea-5532-4ed2-a09a-ac3f32674dcf: # Panel Section
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: panelSection
    instructions: null
    name: 'Panel Section'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 572450533
      columns:
        __assoc__:
          -
            - 0f0c276e-682e-4c12-ac2c-f368cc28ffc2 # Left Panel
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - a784e051-4dbc-4017-ba12-b606222b68cf # Right Panel
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_39_panelsection}}'
      fieldLayout: table
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: panels
name: Panels
sortOrder: 3
