field: 3d0f34fc-321b-4382-a86b-98aebbfa2530 # Global SEO Fields
fieldLayouts:
  2b2d22c4-6783-4d67-863d-db464eb798f2:
    tabs:
      -
        elements:
          -
            fieldUid: be35e78d-d134-480b-aed8-e9e0c966be8b # SEOTitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be23f7cc-c155-4f84-80ef-bfca2217ecaf
            warning: null
            width: 100
          -
            fieldUid: a2f67649-5d81-46a0-a14e-9f90177f8ae0 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: afe21b82-d7ed-4fd2-b3dd-2458a95f2cd7
            warning: null
            width: 100
          -
            fieldUid: 17be5eaf-d483-4904-908a-9387a70c6fa0 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 731ed75c-673b-4f14-a236-2f0d6ed25ef5
            warning: null
            width: 100
          -
            fieldUid: 251a3881-3253-4fdf-94d3-01eb0d61a8f6 # Keywords
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ece7095-42ad-489a-ad1e-c8398eea0979
            warning: null
            width: 100
        name: Content
        uid: 832ff127-c22d-4a49-8dd1-0573287ef368
fields:
  17be5eaf-d483-4904-908a-9387a70c6fa0: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:c4100103-0b95-4960-bee7-74876c13e673' # General Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c4100103-0b95-4960-bee7-74876c13e673' # General Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  251a3881-3253-4fdf-94d3-01eb0d61a8f6: # Keywords
    columnSuffix: fdmczebp
    contentColumnType: text
    fieldGroup: null
    handle: keywords
    instructions: null
    name: Keywords
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a2f67649-5d81-46a0-a14e-9f90177f8ae0: # Description
    columnSuffix: lanqjtuk
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: "\"a brief summary of the website\"\r\n\r\n- 50–160 characters long, including spaces\r\n- A page's meta description should intelligently (read: in a natural, active, non-spammy way) employ the keywords that page is targeting, but also create a compelling description that a searcher will want to click.\r\n- Search engines bold keywords in the description when they match search queries. This can draw the eyes of searchers, so match your descriptions to search terms as closely as possible"
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  be35e78d-d134-480b-aed8-e9e0c966be8b: # SEOTitle
    columnSuffix: hzoxyugw
    contentColumnType: text
    fieldGroup: null
    handle: seotitle
    instructions: "\"Primary Keyword – Secondary Keyword | Brand Name\"\r\n\r\n- 50-60 characters long, including spaces\r\n- Although this should be formatted to some degree for search engines, it’s vital that the tag makes perfect sense to humans and reads like a legible sentence."
    name: SEOTitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: settings
name: Settings
sortOrder: 1
