field: 2b752466-a680-4956-b353-c24d023b4612 # Blocks
fieldLayouts:
  0cc3902e-6c41-4b59-bd3b-7ee4a795ee70:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 32ec23d2-a572-4ebd-9123-905fb164fea6 # Column Span
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f5f7e2ef-4f8c-4faf-bb1d-8f3523574243
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 8eb63c4c-f927-41d0-95cc-a6dd08662b34 # Height
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60fada9a-67d4-48ef-936b-433b4dd0c57f
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 26053788-cae4-43f6-8fb3-a4339a9d8aa2
        userCondition: null
fields:
  8eb63c4c-f927-41d0-95cc-a6dd08662b34: # Height
    columnSuffix: rtvbabmg
    contentColumnType: string
    fieldGroup: null
    handle: height
    instructions: null
    name: Height
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - '000'
            -
              - value
              - '--s0'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '100'
            -
              - value
              - '--s1'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '200'
            -
              - value
              - '--s2'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '300'
            -
              - value
              - '--s3'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '400'
            -
              - value
              - '--s4'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '500'
            -
              - value
              - '--s5'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '600'
            -
              - value
              - '--s6'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '700'
            -
              - value
              - '--s7'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  32ec23d2-a572-4ebd-9123-905fb164fea6: # Column Span
    columnSuffix: dbbnmtgb
    contentColumnType: integer(10)
    fieldGroup: null
    handle: columnSpan
    instructions: null
    name: 'Column Span'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: decimal
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
handle: spacerBlock
name: Spacer
sortOrder: 7
