field: 0f0c276e-682e-4c12-ac2c-f368cc28ffc2 # Left Panel
fieldLayouts:
  709d0c89-3eb9-438c-a90b-907ce96c9a3f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 53b3ba8f-6db9-404e-8a23-09bd33a9745f # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0bef8f30-db8f-4161-a19b-f7060c0824dc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9c6486cd-683f-42df-97f3-717b4c4ad3ca # Animate
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b6829367-16c7-4dae-b3a4-87c6449cd439
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: d1ac72c5-5d8b-4362-a40a-63fb26002771 # Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e57b75cd-564f-47e7-b7c0-8d03bcb92407
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 26175b48-dfb7-4432-81d8-ecf00bc597a3
        userCondition: null
fields:
  9c6486cd-683f-42df-97f3-717b4c4ad3ca: # Animate
    columnSuffix: jmbvypxq
    contentColumnType: boolean
    fieldGroup: null
    handle: animate
    instructions: null
    name: Animate
    searchable: false
    settings:
      default: true
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  53b3ba8f-6db9-404e-8a23-09bd33a9745f: # Text
    columnSuffix: tehmsymh
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  d1ac72c5-5d8b-4362-a40a-63fb26002771: # Background Colour
    columnSuffix: mohghklz
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColour
    instructions: null
    name: 'Background Colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - bg-quaternary-main
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: text
name: Text
sortOrder: 1
