field: 2b752466-a680-4956-b353-c24d023b4612 # Blocks
fieldLayouts:
  64768ee3-91c2-4957-a35a-e35f6ef9577f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7fdff696-109b-4df0-8732-365efe2ab544 # Block Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d93c2706-e20e-4693-abea-b1d813b78444
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: c53f9eae-76f9-4d5a-93be-1a662f470edb # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 893fc60e-dff3-4034-bc24-b73ce5c2e555
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f8359f4d-8324-4cf0-885b-f85435aca6b5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f739a68-28c3-4e33-a0bf-c754904f7aef
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: b29841aa-b6f8-4b94-84d7-b3408c528e4e # Button Repeater
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b8ce992-9f11-468f-ac1e-b299814ba8f5
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 7b431ab7-4a7c-4be5-af4f-d235d4007a5b
        userCondition: null
fields:
  7fdff696-109b-4df0-8732-365efe2ab544: # Block Colour
    columnSuffix: puqgozxx
    contentColumnType: string
    fieldGroup: null
    handle: blockColour
    instructions: 'Set block background colour'
    name: 'Block Colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - bg-quaternary-main
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  b29841aa-b6f8-4b94-84d7-b3408c528e4e: # Button Repeater
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonRepeater
    instructions: 'Add buttons to the block'
    name: 'Button Repeater'
    searchable: false
    settings:
      blockTypeFields: 0
      changedFieldIndicator: 299927913
      columns:
        __assoc__:
          -
            - 492d0347-d1c3-42cb-9c22-a6816faf9451 # Button
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 740d3885-3e3e-44bd-b10b-ab2b819555fd # Button Style
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 45392ba9-01f3-4281-b414-c430c7b48c28 # Button Colour
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_1_buttonrepeater}}'
      fieldLayout: matrix
      maxRows: null
      minRows: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: null
      staticField: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  c53f9eae-76f9-4d5a-93be-1a662f470edb: # Text
    columnSuffix: wxbahukt
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f8359f4d-8324-4cf0-885b-f85435aca6b5:
    columnSuffix: eciyowpy
    contentColumnType: string
    fieldGroup: null
    handle: buttonOrientation
    instructions: 'Set button(s) orientation'
    name: 'Button Orientation'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Center
            -
              - value
              - center
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Right
            -
              - value
              - right
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Space Evenly'
            -
              - value
              - space-evenly
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Space Around'
            -
              - value
              - space-around
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Space Between'
            -
              - value
              - space-between
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Even Stretch'
            -
              - value
              - evenStretch
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: textBlock
name: Text
sortOrder: 1
