field: 2b752466-a680-4956-b353-c24d023b4612 # Blocks
fieldLayouts:
  64768ee3-91c2-4957-a35a-e35f6ef9577f:
    tabs:
      -
        elements:
          -
            fieldUid: 7fdff696-109b-4df0-8732-365efe2ab544
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d93c2706-e20e-4693-abea-b1d813b78444
            warning: null
            width: 25
          -
            fieldUid: c53f9eae-76f9-4d5a-93be-1a662f470edb # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 893fc60e-dff3-4034-bc24-b73ce5c2e555
            warning: null
            width: 100
        name: Content
        uid: 7b431ab7-4a7c-4be5-af4f-d235d4007a5b
fields:
  7fdff696-109b-4df0-8732-365efe2ab544:
    columnSuffix: puqgozxx
    contentColumnType: string
    fieldGroup: null
    handle: blockColour
    instructions: 'Set block background colour'
    name: 'Block Colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - bg-quaternary-main
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c53f9eae-76f9-4d5a-93be-1a662f470edb: # Text
    columnSuffix: wxbahukt
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: textBlock
name: Text
sortOrder: 1
