field: 5257ad8b-ba8e-472f-9b95-1ee64ecb69c1 # Slide Content
fieldLayouts:
  2555f016-915c-4c28-8d81-2f6b3b54d4b0:
    tabs:
      -
        elements:
          -
            fieldUid: 3c4e0f9f-a31e-45c2-8929-1b6d83d60fdf # Video Asset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8664885-64ec-4562-b3fe-fffc63f1dad5
            warning: null
            width: 100
        name: Content
        uid: 070e5462-7831-4330-9d71-a0d464603e43
fields:
  3c4e0f9f-a31e-45c2-8929-1b6d83d60fdf: # Video Asset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: videoAsset
    instructions: null
    name: 'Video Asset'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - json
        - video
      defaultUploadLocationSource: 'volume:c4100103-0b95-4960-bee7-74876c13e673' # General Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c4100103-0b95-4960-bee7-74876c13e673' # General Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: video
name: Video
sortOrder: 3
