columnSuffix: ejxnpbfm
contentColumnType: text
fieldGroup: 577b4a42-725d-4f41-a0a6-f312ca733dba # Fonts
handle: bodyFont
instructions: 'Use these fields to define the properties for fonts'
name: 'Body Font'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Font Name'
            -
              - handle
              - fontName
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Font Weight'
            -
              - handle
              - fontWeight
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - '200'
                    -
                      - value
                      - '200'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '300'
                    -
                      - value
                      - '300'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '400'
                    -
                      - value
                      - '400'
                    -
                      - default
                      - true
                -
                  __assoc__:
                    -
                      - label
                      - '500'
                    -
                      - value
                      - '500'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '600'
                    -
                      - value
                      - '600'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '700'
                    -
                      - value
                      - '700'
                    -
                      - default
                      - false
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Font Style'
            -
              - handle
              - fontStyle
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - Serif
                    -
                      - value
                      - Serif
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - Sans-Serif
                    -
                      - value
                      - Sans-Serif
                    -
                      - default
                      - true
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - 'Line Height'
            -
              - handle
              - lineHeight
            -
              - width
              - ''
            -
              - type
              - number
      -
        - col5
        -
          __assoc__:
            -
              - heading
              - Spacing
            -
              - handle
              - spacing
            -
              - width
              - ''
            -
              - type
              - select
            -
              - options
              -
                -
                  __assoc__:
                    -
                      - label
                      - '0'
                    -
                      - value
                      - '--f0'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '1'
                    -
                      - value
                      - '--f1'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '2'
                    -
                      - value
                      - '--f2'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '3'
                    -
                      - value
                      - '--f3'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '4'
                    -
                      - value
                      - '--f4'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '5'
                    -
                      - value
                      - '--f5'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '6'
                    -
                      - value
                      - '--f6'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '7'
                    -
                      - value
                      - '--f7'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '8'
                    -
                      - value
                      - '--f8'
                    -
                      - default
                      - false
                -
                  __assoc__:
                    -
                      - label
                      - '9'
                    -
                      - value
                      - '--f9'
                    -
                      - default
                      - false
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - '200'
        -
          - col3
          - Sans-Serif
        -
          - col4
          - ''
        -
          - col5
          - '--f0'
  maxRows: 1
  minRows: 1
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
