columnSuffix: iajyprlo
contentColumnType: 'decimal(3,2)'
fieldGroup: 577b4a42-725d-4f41-a0a6-f312ca733dba # Fonts
handle: fontRatio
instructions: 'This is a Major Third scale that powers font sizes. All items are calculated off the base size, so change that and cascade across your whole project'
name: 'Font Ratio'
searchable: false
settings:
  decimals: 2
  defaultValue: 1.3
  max: 2.5
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
