columnSuffix: ptpqwvvp
contentColumnType: string
fieldGroup: 04c6669e-c111-4486-981d-d607c6b7bdd5 # Header
handle: headerBehaviour
instructions: null
name: 'Header Behaviour'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - Default
        -
          - value
          - default
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Auto Hide'
        -
          - value
          - autoHide
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
