columnSuffix: null
contentColumnType: string
fieldGroup: 0caf853a-57c2-4d4d-857e-ec44f683607d # Page Builder
handle: heroBuilder
instructions: null
name: 'Hero Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_herobuilder}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
