columnSuffix: nxuykuzy
contentColumnType: string
fieldGroup: 49169920-d20d-4469-bb6a-55f9c094ae82 # Master
handle: masterRowSpacing
instructions: 'Set the space between rows site wide'
name: 'Master Row Spacing'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - None
        -
          - value
          - gap-top-000
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'XX Small'
        -
          - value
          - gap-top-100
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'X Small'
        -
          - value
          - gap-top-200
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Small
        -
          - value
          - gap-top-300
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Medium
        -
          - value
          - gap-top-400
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Large
        -
          - value
          - gap-top-500
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'X Large'
        -
          - value
          - gap-top-600
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'XX Large'
        -
          - value
          - gap-top-700
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
