columnSuffix: otyzxnoh
contentColumnType: integer(10)
fieldGroup: 577b4a42-725d-4f41-a0a6-f312ca733dba # Fonts
handle: maxLineLength
instructions: null
name: 'Max Line Length'
searchable: false
settings:
  decimals: 0
  defaultValue: 100
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
