field: 686319ea-5532-4ed2-a09a-ac3f32674dcf # Panel Section
fieldLayouts:
  4ae036d5-414c-4c4f-9ae1-f96b49c5ca03:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0f0c276e-682e-4c12-ac2c-f368cc28ffc2 # Left Panel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d80c4aef-1609-4629-8971-4ec4cc13a60c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a784e051-4dbc-4017-ba12-b606222b68cf # Right Panel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 801ebb9e-be59-4aeb-8cd4-1a60d6e9c37d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f6ded72f-d6ff-4440-9704-a1a32a93ca1b
        userCondition: null
fields:
  0f0c276e-682e-4c12-ac2c-f368cc28ffc2: # Left Panel
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: leftPanel
    instructions: null
    name: 'Left Panel'
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_leftpanel}}'
      maxBlocks: 1
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  a784e051-4dbc-4017-ba12-b606222b68cf: # Right Panel
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: rightPanel
    instructions: null
    name: 'Right Panel'
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_rightpanel}}'
      maxBlocks: 1
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
