field: 5cbe70f6-1a87-466e-92cd-9430a00c5a3b # Hero Content
fieldLayouts:
  6ae38a56-46a0-4f73-83d8-e6be4e6360ba:
    tabs:
      -
        elements:
          -
            fieldUid: 6614ecb0-f4c5-450d-9705-20eae03231ee # Hero Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79e5c94a-3905-4d92-b507-6a8264858b9c
            warning: null
            width: 100
        name: Content
        uid: 14b75b26-cd1e-4b2b-80dc-7832382ad005
fields:
  6614ecb0-f4c5-450d-9705-20eae03231ee: # Hero Block
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: heroBlock
    instructions: null
    name: 'Hero Block'
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_heroblock}}'
      maxBlocks: null
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
