field: 1bb528ba-9473-46f5-a4f3-37b18e316d67 # Accordion
fieldLayouts:
  e200a3fa-1bfb-4ae6-9446-b9657b458b9b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 400cc303-7122-4b66-93d7-24595fa00d9e # Accordion Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 01d48a90-9e66-4a96-9f68-96f9c9af6fdd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ccb1c890-467d-4e54-9954-92b1d979b4ac # Accordion Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4c3fdf0-79da-4e17-9b34-2dd67a65ef1d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6862320f-e776-4eee-bd7e-e330d64ba5ae
        userCondition: null
fields:
  400cc303-7122-4b66-93d7-24595fa00d9e: # Accordion Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: accordionTitle
    instructions: null
    name: 'Accordion Title'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ccb1c890-467d-4e54-9954-92b1d979b4ac: # Accordion Content
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: accordionContent
    instructions: null
    name: 'Accordion Content'
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_accordioncontent}}'
      maxBlocks: null
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
