field: e84a8308-763b-47b1-9f67-d92c52577869 # Related Entry
fieldLayouts:
  97f07937-fd3e-4003-b339-5ff92e3c3670:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ead3f394-0828-4cfa-a4a2-7d1b8c40c192 # Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0602e41-f7fb-4444-9698-1e3d29799c73
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d02337d8-3537-4841-87b1-61c5d157e58c # Popup
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a2ef964-327e-4bce-8ec5-c989b8df92ff
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 03e10793-6434-4680-8eda-9f5c82acbaa0 # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1f42fd8-d7c0-4648-8071-a35e3e1f2817
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d44b3f6f-7eb7-424d-a7d0-862c53334fe1 # Hide Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a04a5a78-cf8c-40c7-a01a-1333e2f356a8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f797021d-c9c1-444f-a81d-f716d4892535
        userCondition: null
fields:
  03e10793-6434-4680-8eda-9f5c82acbaa0: # Button Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: null
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d02337d8-3537-4841-87b1-61c5d157e58c: # Popup
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: popup
    instructions: null
    name: Popup
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  d44b3f6f-7eb7-424d-a7d0-862c53334fe1: # Hide Button
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: hideButton
    instructions: null
    name: 'Hide Button'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  ead3f394-0828-4cfa-a4a2-7d1b8c40c192: # Entry
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entry
    instructions: null
    name: Entry
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: 1
      minRelations: 1
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: null
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
