field: 10db7aae-6270-451e-9f2f-c279cc5e3af0 # __blank__
fieldLayouts:
  0568d2e9-332d-4488-abcf-154ad0cc46e2:
    tabs:
      -
        elements:
          -
            fieldUid: 2b752466-a680-4956-b353-c24d023b4612 # Blocks
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f495c516-271d-4f14-a5d0-5d42ef258431
            warning: null
            width: 100
        name: Content
        uid: 21c83e6a-a871-4866-adfa-32569560b237
fields:
  2b752466-a680-4956-b353-c24d023b4612: # Blocks
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: blocks
    instructions: 'Blocks are used to display different content within a row'
    name: Blocks
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_blocks}}'
      maxBlocks: null
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
