field: e39fb6a1-25c9-4954-bcd1-85d45cd9be98 # __blank__
fieldLayouts:
  f7baccae-dc08-4b3e-bcd4-3d6943c2bb83:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ddfc31c2-3d66-4da3-bd8b-d189e314b086 # Card Background Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86822ec6-98d3-4e3c-93ac-965d064912c5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 63f27bf0-bfd3-4591-8b86-10955f3cfbcf # Order
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3e9ea3e-b85b-421f-b2df-5512fc730453
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2b9aa9b3-4b17-4a59-aa1c-74a0a86dee9b # Button Colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0be8043e-5a1e-4c13-b493-14725d7a6f12
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ac31927-2736-48ef-92ba-8933246dd5ae # Button Style
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 48faa3d7-4538-4f98-a19e-73fb1c19be95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 37b10ad2-1a23-4c38-8077-0b83551e9492 # Layout
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f9a6aadd-fc0e-43b2-a446-615de6364416
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b8e964d1-7982-446a-8fd5-a0b85e16bcb5
        userCondition: null
fields:
  2b9aa9b3-4b17-4a59-aa1c-74a0a86dee9b: # Button Colour
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonColour
    instructions: null
    name: 'Button Colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Master
            -
              - value
              - master
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Inherit
            -
              - value
              - ''
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quarternary
            -
              - value
              - bg-quarternary-main
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  3ac31927-2736-48ef-92ba-8933246dd5ae: # Button Style
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonStyle
    instructions: null
    name: 'Button Style'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - primary
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Ghost
            -
              - value
              - ghost
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - secondary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Full Width'
            -
              - value
              - 'primary full-width'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  37b10ad2-1a23-4c38-8077-0b83551e9492: # Layout
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: layout
    instructions: 'Select a layout option to display the selected entry type.'
    name: Layout
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_layout}}'
      maxBlocks: null
      minBlocks: null
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  63f27bf0-bfd3-4591-8b86-10955f3cfbcf: # Order
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: order
    instructions: null
    name: Order
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - 'Menu Order'
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Newest First'
            -
              - value
              - 'postDate desc'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Oldest First'
            -
              - value
              - 'postDate asc'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  ddfc31c2-3d66-4da3-bd8b-d189e314b086: # Card Background Colour
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardBackgroundColour
    instructions: null
    name: 'Card Background Colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - bg-light-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - bg-dark-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - bg-primary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - bg-secondary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - bg-tertiary-main
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - bg-quaternary-main
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
