field: b12af4cb-33ee-45d8-839f-cc631bdec7aa # Background Image
fieldLayouts:
  71fbe73e-025e-4393-a31a-3ef3168238ca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e6787659-8762-438e-9d5b-f250484899e1 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f4b9400-2969-4b20-a287-5396b075320a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3125d32f-3f3e-476e-be41-570a311f535d # Overlay
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ef835d2-88cb-4922-af6c-13e2b73bb2b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8198fa56-c374-4bf1-a89b-e12f9424c957 # Overlay Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 024924eb-53c5-477c-adc6-4835d6c63a8c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 65157ff9-c335-43fb-8fe6-c55b6a446515 # Opacity
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc32a0bd-eb30-40e8-a9b5-c9ec545afe0f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dc08a4ab-5fa4-44d6-ba58-5881bc075598 # Blend Mode
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63e9f469-21d1-4e5b-8f6c-43b060b6f58b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8fa95921-a2dc-40ea-b89d-fbedaeacb68d
        userCondition: null
fields:
  3125d32f-3f3e-476e-be41-570a311f535d: # Overlay
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: overlay
    instructions: null
    name: Overlay
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Light
            -
              - value
              - 'overlay bg-light-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dark
            -
              - value
              - 'overlay bg-dark-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - 'overlay bg-primary-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - 'overlay bg-secondary-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Tertiary
            -
              - value
              - 'overlay bg-tertiary-main'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quaternary
            -
              - value
              - 'overlay bg-quaternary-main'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  8198fa56-c374-4bf1-a89b-e12f9424c957: # Overlay Type
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: overlayType
    instructions: null
    name: 'Overlay Type'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Radial
            -
              - value
              - radial
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  65157ff9-c335-43fb-8fe6-c55b6a446515: # Opacity
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: opacity
    instructions: null
    name: Opacity
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - '0.1'
            -
              - value
              - o-01
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '0.2'
            -
              - value
              - o-02
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '0.3'
            -
              - value
              - o-03
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '0.4'
            -
              - value
              - o-04
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '0.5'
            -
              - value
              - o-05
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - '0.6'
            -
              - value
              - o-06
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '0.7'
            -
              - value
              - o-07
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '0.8'
            -
              - value
              - o-08
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '0.9'
            -
              - value
              - o-09
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  dc08a4ab-5fa4-44d6-ba58-5881bc075598: # Blend Mode
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: blendMode
    instructions: null
    name: 'Blend Mode'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Multiply
            -
              - value
              - multiply
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Overlay
            -
              - value
              - overlay
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  e6787659-8762-438e-9d5b-f250484899e1: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:c4100103-0b95-4960-bee7-74876c13e673' # General Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c4100103-0b95-4960-bee7-74876c13e673' # General Uploads
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
