defaultPlacement: end
enableVersioning: true
handle: caseStudies
name: 'Case Studies'
propagationMethod: all
siteSettings:
  0f153ab3-0b96-4f89-82fd-cd94590bc9b7: # Craft Four
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: 'case-studies/{slug}'
type: channel
