defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  0f153ab3-0b96-4f89-82fd-cd94590bc9b7: # Craft Four
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: '{entry.last().uri}/{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 2902a809-f07b-4970-b59f-9e00fa8e4787
type: structure
