defaultPlacement: end
enableVersioning: true
handle: posts
name: Posts
propagationMethod: all
siteSettings:
  0f153ab3-0b96-4f89-82fd-cd94590bc9b7: # Craft Four
    enabledByDefault: true
    hasUrls: true
    template: entry.twig
    uriFormat: 'posts/{slug}'
type: channel
